name: Trigger Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
      - name: Repository dispatch to portfolio-deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: chrishoward/portfolio-deploy
          event-type: trigger-deploy
